### ISSUE TITLE
Marker cluster seems to interfere with popupOpen=true on markers

### ISSUE THREAD

**Issue by ianpetzer** [canufeel/ember-leaflet-marker-cluster#7]
Hi,

Thanks for this awesome library. 

I currently have some markers on a map, and one of the markers has a popup which is opened by default if you're not on mobile. You can see it here: https://www.timbuktutravel.com/trip/luangwa-the-lake-of-stars

The only problem I'm having is that as soon as I include the {{marker-cluster-layer}}, it seems to cause ember-leaflet to ignore the popupOpen=true on the marker.

Do you have any ideas how I could work around this?

Thanks!
Ian

**Comment by canufeel** [comment]
@ianpetzer Hello Ian! Why do you want to put the marker with pop-up enabled by default in the cluster?
Why not put it into separate array? Anyway you are marking it some how so you know that it should be enabled by default.
Anyways i would investigate on the issue and test this case to fix it.

**Comment by IAmJulianAcosta** [comment]
Related: https://github.com/miguelcobain/ember-leaflet/issues/69 

I investigate what was happening, is in the issue, but the issue is that `L.marker.onAdd` is firing after `openPopup` and that's why isn't working.

**Comment by cesarizu** [comment]
With versions `ember-leaflet-marker-cluster@0.0.3` and `ember-leaflet@2.2.8-beta.3` I get the following error when putting the markers with popups in a `marker-cluster-layer`:

```
app.js:8Cannot read property 'addEventListener' of undefined TypeError: Cannot read property 'addEventListener' of undefined
    at Class._addPopupListeners (http://dev.hauseful.com/assets/vendor.js:111724:23)
    at Class.didCreateLayer (http://dev.hauseful.com/assets/vendor.js:111673:14)
    at Class.superWrapper [as didCreateLayer] (http://dev.hauseful.com/assets/vendor.js:39599:22)
    at Class.layerSetup (http://dev.hauseful.com/assets/vendor.js:110875:12)
    at Array.<anonymous> (http://dev.hauseful.com/assets/vendor.js:49965:36)
    at Array.forEach (native)
    at Array.invoke (http://dev.hauseful.com/assets/vendor.js:49961:12)
    at Class.didInsertElement (http://dev.hauseful.com/assets/vendor.js:110773:30)
    at Class.superWrapper [as didInsertElement] (http://dev.hauseful.com/assets/vendor.js:39599:22)
    at Class.trigger (http://dev.hauseful.com/assets/vendor.js:58492:23)
```

The same markers without popups or outside the cluster work correctly. Where could I start debugging this issue?

**Comment by jsArgus** [comment]
Yeah still seeing this bug. 

-  "ember-leaflet": "3.0.8",
-  "ember-leaflet-marker-cluster": "0.0.5",
-   "leaflet": "^1.0.0",
-   "leaflet.markercluster": "~1.0.0"

**Comment by miguelcobain** [comment]
Please reopen if still an issue in latest ember-leaflet beta and latest ember-leaflet-marker-cluster.
